//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxCRUD_Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Phone { get; set; }
        public double Salary { get; set; }
        public string Gender { get; set; }
        public long DepartmentID { get; set; }
        public bool IsActive { get; set; }
        public string Address { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
